export const copy = {
  appName: 'Grade 6 English Class',
  intro: '6 ශ්‍රේණිය',
  classYear: '2027',
  infoTitle: 'මෙවර ශිෂ්‍යත්ව විභාගය අවසන් කළ දරුවන් සඳහා',
  infoPlaceholder: '',
  formTitle: 'ඔබේ දරුවා ලියාපදිංචි කරන්න',
  formHelp: 'සිසුවාගේ නම සහ දෙමාපියන්ගේ හෝ භාරකරුගේ WhatsApp අංකය ඇතුළත් කරන්න.',
  studentLabel: 'සිසුවාගේ නම',
  studentPlaceholder: 'සිසුවාගේ නම ඇතුළත් කරන්න',
  phoneLabel: 'WhatsApp අංකය',
  phonePlaceholder: '07X XXXXXXX',
  submit: 'ලියාපදිංචි වන්න',
  successTitle: 'ලියාපදිංචිය සාර්ථකයි! 🎉',
  successMessage: 'සිසුවා සාර්ථකව ලියාපදිංචි කර ඇත.',
  successHelp: 'කරුණාකර මෙම තහවුරු කිරීම සුරක්ෂිතව තබා ගන්න.',
  another: 'තවත් සිසුවෙකු ලියාපදිංචි කරන්න',
  registration: 'ලියාපදිංචිය',
  privacyNote: 'ඔබගේ තොරතුරු පන්ති ලියාපදිංචිය සඳහා පමණක් භාවිතා කරයි.',
  invalidName: 'කරුණාකර සිසුවාගේ සම්පූර්ණ නම ඇතුළත් කරන්න.',
  invalidPhone: 'කරුණාකර 0712345678 වැනි වලංගු ශ්‍රී ලාංකික දුරකථන අංකයක් ඇතුළත් කරන්න.',
  notConfigured: 'ලියාපදිංචි කිරීම තවම සකසා නැත. කරුණාකර පසුව නැවත උත්සාහ කරන්න.',
  duplicate: 'මෙම WhatsApp අංකය දැනටමත් ලියාපදිංචි කර ඇත.',
  genericError: 'යම් දෝෂයක් සිදු විය. කරුණාකර නැවත උත්සාහ කරන්න.',
  networkError: 'අන්තර්ජාලයට සම්බන්ධ විය නොහැක. කරුණාකර නැවත උත්සාහ කරන්න.',
  submitting: 'ලියාපදිංචි කරමින්…'
} as const
